### ISSUE TITLE
can't install the plugin

### ISSUE THREAD

**Issue by imeed166** [yajamon/obsidian-command-alias-plugin#13]
When I try to install the plugin from obsidian, I get this error.
![image](https://user-images.githubusercontent.com/38974541/131331845-805165f1-6af8-4f93-a0a7-93b7679fb3b4.png)

**Comment by yajamon** [comment]
@imeed166 
I think the reason is that 1.1.0 was a draft so far.
Please try again.

**Comment by imeed166** [comment]
It works now, thank you.
