### ISSUE TITLE
"Missing command. Run this and try rebiding" is always displayed at startup.

### ISSUE THREAD

**Issue by qawatake** [yajamon/obsidian-command-alias-plugin#17]
### Is your feature request related to a problem? Please describe.

I always get a "Missin command. Run this and try rebiding" message and have to do rebiding manually when I start obsidian on PC or mobile.
I'm happy if rebiding is done automatically at startup and  I can immediately use aliases.

**Comment by yajamon** [comment]
The Aliase plugin works smoothly when loaded after other plugins.
However, the loading order of the plugins is determined by "Obsidian Core".

For now, I've decided to request a reload at the latest time the user needs to execute the alias (that is, when executing a command with the alias).

I'm looking for an idea for this request.

**Comment by qawatake** [comment]
I found a temporary solution. But, this solution is inessential because it utilizes another plugin "QuickAdd".

By following the following steps, I can use aliases without reloading manually.
1. Install "QuickAdd" plugin and enable it.
2. Open the setting page of "QuickAdd"
3. _Manage Macros_ -> _Add macro_ -> _Run on plugin load_ -> _Configure_ 
4. _Obsidian command_ -> `Command Alias: <<myalias>>: Missing command. Run this and try rebinding`

I think this temporary solution will be a clue to development.

**Comment by qawatake** [comment]
I wrote a code that will reduce "Missing command" messages.
https://github.com/qawatake/obsidian-command-alias-plugin/commit/866fd4fab62eb40cfb1534ec5589cb7621eafda4

**Comment by yajamon** [comment]
@qawatake  That's a great idea. I missed that `onload` is `async`.

I will try it too. I have some ideas I would like to add. (Handling of Promise. Setting timeout and number of trials.)
