### ISSUE TITLE
Alias list in the Preferences panel should be sorted by name.

### ISSUE THREAD

**Issue by yajamon** [yajamon/obsidian-command-alias-plugin#28]
### Is your feature request related to a problem? Please describe.

In the current order (in order of addition), it is difficult to find a particular alias with many aliases.
We also cannot search in the settings panel.

### Describe the solution you'd like

Add an option to sort by name to the alias list in the Preferences panel.

### Describe alternatives you've considered

None.

### Additional context

None.

**Comment by chenxin0397** [comment]
me too
