### ISSUE TITLE
adding alias at the end of the existing name or start.

### ISSUE THREAD

**Issue by 1C0D** [yajamon/obsidian-command-alias-plugin#34]
I think it's not 's a great idea to create more commands (they are already a lot with installed plugins)
I would see maybe as an option, the possibility to add the alias before or after the existing name
alias | existing name
and a checkbox [x]start/end in the modal before

**Comment by yajamon** [comment]
Each command has a plugin that is its owner.
Violating proprietary rights and tampering with them is not a good idea.
