### ISSUE TITLE
[Feature Request] Support command prompt window like `Quickadd`

### ISSUE THREAD

**Issue by Quorafind** [yajamon/obsidian-command-alias-plugin#4]
Is it doable add a feature to quick find the command by using prompt list? Like plugin `Quickadd`

![image](https://user-images.githubusercontent.com/13215013/130410597-c9ba01c2-41d7-45fd-a13f-048e22343a8c.png)

**Comment by yajamon** [comment]
I also want this feature.

**Comment by yajamon** [comment]
https://github.com/obsidianmd/obsidian-api/blob/bde556afa033e909ebfb9fcee8f5ef288276f78f/obsidian.d.ts#L1136-L1164
This may be relevant.
